# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20160406_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemodData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload_demod', models.FileField(blank=True, null=True, upload_to=b'data_payloads')),
            ],
        ),
        migrations.RemoveField(
            model_name='data',
            name='payload_demode',
        ),
        migrations.AddField(
            model_name='demoddata',
            name='data',
            field=models.ForeignKey(related_name='demoddata', on_delete=django.db.models.deletion.CASCADE, to='base.Data'),
        ),
    ]
