# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20160406_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellite',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
