# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-07 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20160507_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellite',
            name='manual_tle',
            field=models.BooleanField(default=False),
        ),
    ]
