# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_data_waterfall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='vetted_status',
            field=models.CharField(choices=[(b'unknown', b'Unknown'), (b'verified', b'Verified'), (b'data_not_verified', b'Has Data, Not Verified'), (b'no_data', b'No Data')], default=b'unknown', max_length=20),
        ),
    ]
