# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20170205_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='max_altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='rise_azimuth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='set_azimuth',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
