# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_antenna_frequency_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antenna',
            name='frequency',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='antenna',
            name='frequency_max',
            field=models.PositiveIntegerField(),
        ),
    ]
